services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  mailcatcher:
    image: sj26/mailcatcher
    restart: always
    environment:
      VIRTUAL_HOST: ${MAILCATCHER_VIRTUAL_HOST}
      VIRTUAL_PORT: 1080
    ports:
      - 1080:1080

  app:
    build: .
    image: ghcr.io/kowtom/zm
    env_file: .env
    volumes:
      - static:/app/src/static
    ports:
      - 127.0.0.1:8000:8000

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "443:443"
    volumes:
      - static:/var/www/static
      - ./nginx:/etc/nginx/vhost.d
      - ./ssl:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
  postgres:
  static:
